name: Test Autocode Generator
description: Testing the autocode generator
author:
  name: Patrick Maciel
  email: patrickmaciel.info@gmail.com
  url: 'http://www.patrickmaciel.com'
copyright: 2015 Patrick Maciel
